version: "3"

services:
  web:
    build: .
    ports:
     - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      DATABASE_HOST: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rubycoin_development

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rubycoin_development
    ports:
      - "5433:5432"
    volumes:
      - db_v1:/var/lib/postgresql/data

  redis:
    image: redis

volumes:
  db_v1:
